module "elasticbeanstalk" {
  source                = "../../"
  application_key       = var.application_key
  application_name      = var.application_name
  asg-instanceport      = var.asg-instanceport
  asg-listenerport      = var.asg-listenerport
  asg-maxsize           = var.asg-maxsize
  asg-minsize           = var.asg-minsize
  common_tags           = var.common_tags
  CrossZone             = var.CrossZone
  healthcheck           = var.healthcheck
  ImageId               = var.ImageId
  instance_size         = var.instance_size
  LogPublicationControl = var.LogPublicationControl
  ManagedActions        = var.ManagedActions
  name                  = var.name
  PreferredStartTime    = var.PreferredStartTime
  private_tag           = var.private_tag
  RetentionInDays       = var.RetentionInDays
  stack_reg_ex          = var.stack_reg_ex
  StreamLogs            = var.StreamLogs
  UpdateLevel           = var.UpdateLevel
  VpcNameTag            = var.VpcNameTag
}
